from pico2d import *
import math
open_canvas()
grass=load_image('grass.png')
character=load_image('character_move.png')
grass.draw_now(400,30)
character.draw_now(400,90)
x=0
y=90
frame=0
count=0
while(True):
    angle=0
    if(count==0):
        while(x<750):
            clear_canvas()
            grass.draw(400,30)
            character.clip_draw(frame*100,0,100,100,x,y)
            update_canvas()
            frame=(frame+1)%8
            x+=5
            delay(0.01)
            get_events()
        while(y<550):
            clear_canvas()
            grass.draw(400,30)
            character.clip_draw(frame*100,0,100,100,x,y)
            update_canvas()
            frame=(frame+1)%8
            y+=5
            delay(0.01)
            get_events()
        while(x>20):
            clear_canvas()
            grass.draw(400,30)
            character.clip_draw(frame*100,0,100,100,x,y)
            update_canvas()
            frame=(frame+1)%8
            x-=5
            delay(0.01)
            get_events()
        while(y>90):
            clear_canvas()
            grass.draw(400,30)
            character.clip_draw(frame*100,0,100,100,x,y)
            update_canvas()
            frame=(frame+1)%8
            y-=5
            delay(0.01)
            get_events()
        while(x<375):
            clear_canvas()
            grass.draw(400,30)
            character.clip_draw(frame*100,0,100,100,x,y)
            update_canvas()
            frame=(frame+1)%8
            x+=5
            delay(0.01)
            get_events()
        count=1
    if(count==1):        
        while(angle<6.28):
            clear_canvas()
            grass.draw(400,30)
            character.clip_draw(frame*100,0,100,100,x,y)
            update_canvas()
            frame=(frame+1)%8
            x=400+(math.sin(angle)*250)
            y=340-(math.cos(angle)*250)
            angle+=0.01
            delay(0.01)
            get_events()
        count=0            

